name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated to v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1 # Ensure the region is set

    - name: Build Docker image
      run: |
        docker build -t 211125452449.dkr.ecr.us-east-1.amazonaws.com/my-app:latest .

    - name: Push Docker image to Amazon ECR
      run: |
        docker push 211125452449.dkr.ecr.us-east-1.amazonaws.com/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated to v3
    
    - name: Set up kubectl
      uses: aws-actions/configure-kubeconfig@v2
      with:
        aws-region: us-east-1
        cluster-name: my-eks-cluster
    
    - name: Deploy to Amazon EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
